repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff
        args: [--fix]
      # ruff-format runs on commit but not on --all-files to avoid huge diffs
      - id: ruff-format
        stages: [commit]
