services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.11
    command:
      - redpanda start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      - --advertise-kafka-addr=INTERNAL://redpanda:9092,EXTERNAL://localhost:19092
    ports:
      - "19092:19092"  # external kafka
      - "9644:9644"    # admin
    networks:
      - redpanda-net

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    environment:
      KAFKA_BROKERS: "redpanda:9092"
    ports:
      - "8080:8080"
    networks:
      - redpanda-net
    depends_on:
      - redpanda

networks:
  redpanda-net:
    driver: bridge

